# Generated by Django 5.0.4 on 2024-05-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flight_Name', models.CharField(default='None', max_length=100)),
                ('From', models.CharField(default='None', max_length=100)),
                ('To', models.CharField(default='None', max_length=100)),
                ('Date', models.DateField(default=None)),
                ('Price', models.PositiveIntegerField()),
            ],
        ),
    ]
