# Generated by Django 5.0.4 on 2024-05-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='Duration',
            field=models.CharField(default='1 Hour', max_length=100),
        ),
    ]
