# Generated by Django 5.0.4 on 2024-06-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0003_category_fly_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TicketNo', models.PositiveIntegerField()),
                ('Name', models.CharField(default='None', max_length=100)),
                ('Flight_Name', models.CharField(default='None', max_length=100)),
                ('From', models.CharField(default='None', max_length=100)),
                ('To', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
