# Generated by Django 5.0.4 on 2024-06-05 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0004_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.PositiveIntegerField()),
                ('Gender', models.CharField(max_length=100)),
                ('fly_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fly.fly')),
            ],
        ),
    ]
